import test, { mock } from "node:test"; import assert from "node:assert/strict"; import axios from "axios"; import fs from "node:fs";
import { DurationValidator } from "../src/modules/automation/duration-validator";
import { DuplicateDetector } from "../src/modules/automation/duplicate-detector";
import { StoryFormatSelector } from "../src/modules/automation/story-format-selector";
import { VoiceSelector } from "../src/modules/automation/voice-selector";
import { QualityControlService } from "../src/modules/automation/quality-control.service";
import { PlatformMetadataService } from "../src/modules/automation/metadata.service";
import { providerRetryDelayMs, isQueuedWorkflowFailure, isRateLimitFailure, isRetryableResearchFailure, isTemporaryFailure, retryDelayMs, shouldRetryResearchFailure } from "../src/modules/automation/retry-policy";
import { AutomationRunCoordinator } from "../src/modules/automation/automation-run-coordinator";
import { NicheConfigService } from "../src/modules/automation/niche-config.service";
import { ScheduleService } from "../src/modules/automation/schedule.service";
import { TopicRotationService } from "../src/modules/automation/topic-rotation.service";
import { AUTOMATION_MODES, CONTENT_TYPES, STORY_FORMATS, VISUAL_TYPES } from "../src/modules/automation/automation.types";
import { AutomationService, automationRetryOptions, bullmqJobId, projectDailyIdempotencyKey, workflowIdempotencyKey } from "../src/modules/automation/automation.service";
import { createProjectBodySchema } from "../src/modules/validators/project.validator";
import { createProjectRoutes } from "../src/routes/project/project.routes";
import { AppError } from "../src/common/errors/app-error";
import { TopicResearchService } from "../src/modules/automation/topic-research.service";
import type { NicheProfile, TopicCandidate, VoiceProfile } from "../src/modules/automation/automation.types";
import { RedditApiClient, RedditService, type RedditPost } from "../src/modules/services/reddit/reddit.service";
import { clipUploadIdempotencyKey, isSupportedClipMime, validateClipMedia } from "../src/modules/services/clipQueue/clip-queue.service";
import { QueuedClipModel } from "../src/modules/models/queued-clip.model";
import { NicheProfileModel } from "../src/modules/models/niche-profile.model";
import { RedditSourceModel } from "../src/modules/models/reddit-source.model";
import { QueueService } from "../src/modules/services/queue/queue.service";
import { AUTOMATION_RATE_LIMITER, createWorkerOptions, providerFailureMetadata, shouldRetryAutomationFailure } from "../src/modules/automation/automation-worker-policy";

const profile: NicheProfile={id:"sports",name:"Sports",tones:["energetic"],defaultTone:"energetic",targetAudience:["fans"],preferredVoice:{energy:.9,speed:1.08,intensity:.8,traits:["energetic","confident"]},preferredVoiceCharacteristics:{energy:.9,speed:1.08,intensity:.8,traits:["energetic","confident"]},visualStyle:"sports",contentRestrictions:[],preferredTopicCategories:["records"],topicCategories:["records"],preferredStoryFormats:["record_breaking_moment","controversy"],allowedStoryFormats:["record_breaking_moment","controversy"],hashtagCategories:["sports"],hashtagStrategy:["sports"],researchRequirements:[],language:"en",defaultLanguage:"en",region:"US",targetRegion:"US"};
const candidate: TopicCandidate={topic:"The runner who broke the world record",title:"The Record Nobody Expected",summary:"A runner broke a verified world record.",storyAngle:"The final attempt",importantEntities:["Runner A"],dates:["2024"],events:["World record final"],keywords:["runner","record"],sourceLinks:["https://example.org/a","https://example.org/b"],disputedFacts:[],factualConfidence:.9,scores:{curiosity:.9,emotionalImpact:.8,shortFormPotential:.9,nicheRelevance:1,originality:.8,retentionPotential:.9}};

test("duration targets sixty seconds by speaking rate",()=>{const d=new DurationValidator();assert.deepEqual(d.targetWordRange(60,150),{min:138,target:150,max:162});assert.equal(d.validate(Array(150).fill("word").join(" "),60,150).valid,true)});
test("format selector uses topic signals",()=>assert.equal(new StoryFormatSelector().select(profile,candidate),"record_breaking_moment"));
test("voice selector chooses energetic matching voice and fallback",()=>{const voices:VoiceProfile[]=[{id:"fast",provider:"x",languages:["en"],gender:"male",traits:["energetic","confident"],energy:.9,speed:1.08,intensity:.8,accents:["neutral"],costPerMillionCharactersUsd:0,dailyUsageLimit:null,priority:1,enabled:true},{id:"calm",provider:"x",languages:["en"],gender:"male",traits:["calm"],energy:.2,speed:.9,intensity:.2,accents:["neutral"],costPerMillionCharactersUsd:0,dailyUsageLimit:null,priority:1,enabled:true}];assert.equal(new VoiceSelector().select(profile,voices,"record_breaking_moment","en").selected.id,"fast")});
test("semantic duplicate catches renamed same event",()=>{const detector=new DuplicateDetector();const history=[{id:"1",title:"The Football Match That Started a War",topic:"Football War",normalizedTopic:"football war",keywords:["football","war"],importantEntities:["Honduras","El Salvador"],events:["Football War"],storyAngle:"match triggered conflict",script:"A football match became linked to a war",contentEmbedding:detector.embedding("football match linked to Honduras El Salvador war")} as never];const next={...candidate,topic:"The Soccer Game That Caused a Real War",title:"Soccer Caused a War",summary:"A soccer match was linked to conflict",importantEntities:["Honduras","El Salvador"],events:["Football War"],keywords:["soccer","war"],storyAngle:"match triggered conflict"};assert.equal(detector.compare(next,history,.7).duplicate,true)});
test("different angle can remain below strict threshold",()=>{const detector=new DuplicateDetector();const history=[{id:"1",title:"Match Started a War",topic:"Football War",normalizedTopic:"football war",keywords:["match","war"],importantEntities:["National Team"],events:["Football War"],storyAngle:"causes of war",contentEmbedding:detector.embedding("causes of the war")} as never];const next={...candidate,topic:"How the War Changed the National Football Team",importantEntities:["National Team"],events:["Postwar rebuilding"],storyAngle:"long term effect on players"};assert.equal(detector.compare(next,history,.85).duplicate,false)});
test("metadata respects YouTube title limit",()=>assert.ok(new PlatformMetadataService().build({...candidate,title:"x".repeat(150)},profile,"youtube").title.length<=100));
test("QC allows a render outside duration tolerance and records a warning",()=>{
  const result=new QualityControlService().check({
    content:{...candidate,script:"x",voiceId:"v",targetDurationSeconds:60} as never,
    finalVideo:{durationSeconds:48.44,width:1080,height:1920,hasAudio:true,blankSceneCount:0,subtitleCount:1,unauthorizedWatermark:false,mediaRightsVerified:true},
    accountActive:true
  });
  assert.equal(result.passed,true);
  assert.deepEqual(result.critical,[]);
  assert.ok(result.warnings.includes("render duration is outside tolerance"));
});
test("QC allows every detected finding and preserves them as warnings",()=>{
  const result=new QualityControlService().check({content:{...candidate,sourceLinks:[],script:"",voiceId:"",targetDurationSeconds:60} as never,accountActive:false});
  assert.equal(result.passed,true);
  assert.deepEqual(result.critical,[]);
  assert.ok(result.warnings.includes("assigned account credentials are inactive"));
  assert.ok(result.warnings.includes("important facts do not have valid source URLs"));
  assert.ok(result.warnings.includes("narration script is missing"));
  assert.ok(result.warnings.includes("voice selection is missing"));
  assert.ok(result.warnings.includes("final video is missing"));
});
test("QC allows a valid render without quality warnings",()=>{
  const result=new QualityControlService().check({
    content:{...candidate,script:"x",voiceId:"v",targetDurationSeconds:60} as never,
    finalVideo:{durationSeconds:60,width:1080,height:1920,hasAudio:true,blankSceneCount:0,subtitleCount:1,unauthorizedWatermark:false,mediaRightsVerified:true},
    accountActive:true
  });
  assert.equal(result.passed,true);
  assert.deepEqual(result.critical,[]);
  assert.deepEqual(result.warnings,[]);
});
test("retry delay is exponential and capped",()=>{assert.equal(retryDelayMs(1),5000);assert.equal(retryDelayMs(20),300000)});
test("niche selection loads all editable profiles and 60-second default",()=>{const config=new NicheConfigService();assert.equal(config.listNiches().length,7);assert.equal(config.getNicheOrThrow("philippine_history").region,"PH");assert.equal(config.getDefaults().targetDurationSeconds,60)});
test("daily scheduler respects configured active days",()=>{const next=new ScheduleService().nextRun("Asia/Manila","19:00",[1],new Date("2026-07-13T12:00:00Z"));assert.equal(next.getUTCDay(),1);assert.ok(next>new Date("2026-07-13T12:00:00Z"))});
test("topic rotation blocks a recently repeated entity",()=>{const history=[{importantEntities:["Michael Jordan"],storyFormat:"hero_story"} as never];assert.ok(new TopicRotationService().violations({...candidate,importantEntities:["Michael Jordan"]},history).length>0)});
test("publishing modes require an intentional choice",()=>assert.deepEqual(AUTOMATION_MODES,["fully_automatic","approval_before_upload","draft_only"]));
test("unified content and visual registries contain every supported mode",()=>{assert.deepEqual(CONTENT_TYPES,["FACELESS_NICHE","REDDIT_STORY","CLIP_UPLOAD"]);assert.deepEqual(VISUAL_TYPES,["IMAGE","ANIMATED","AUTO"])});
test("final research fallback preserves safe Groq quota details for queue retry",async()=>{const post=mock.method(axios,"post",async()=>{throw{isAxiosError:true,message:"Request failed with status code 429",response:{status:429,data:{error:{message:"Rate limit reached",code:"rate_limit_exceeded"}},headers:{"retry-after":"75","x-ratelimit-limit-requests":"250","x-ratelimit-remaining-requests":"241","x-ratelimit-reset-requests":"51m","x-ratelimit-limit-tokens":"70000","x-ratelimit-remaining-tokens":"1200","x-ratelimit-reset-tokens":"48s"}}}});try{const service=new TopicResearchService("test-key","groq/compound-mini","https://api.groq.test/openai/v1",["qwen/qwen3.6-27b","llama-3.1-8b-instant"]);await assert.rejects(()=>service.generate({profile,language:"en",region:"US",recentTopics:[],recentEntities:[]}),error=>{assert.ok(error instanceof AppError);assert.equal(error.code,"GROQ_RATE_LIMITED");assert.match(error.message,/Automatic retries/);assert.deepEqual(error.details,{provider:"groq",providerCode:"rate_limit_exceeded",providerMessage:"Rate limit reached",retryAfter:"75",limitRequests:"250",remainingRequests:"241",resetRequests:"51m",limitTokens:"70000",remainingTokens:"1200",resetTokens:"48s"});return true});assert.equal(post.mock.callCount(),3)}finally{post.mock.restore()}});
test("small Groq Compound 413 responses are translated into a retryable provider failure with safe diagnostics",async()=>{const post=mock.method(axios,"post",async()=>{throw{isAxiosError:true,message:"Request failed with status code 413",response:{status:413,data:{error:{message:"Request Entity Too Large",code:"request_too_large"}},headers:{"x-request-id":"req_413_test"}}}});try{const service=new TopicResearchService("test-key","groq/compound-mini","https://api.groq.test/openai/v1");await assert.rejects(()=>service.generate({profile,language:"en",region:"US",recentTopics:[],recentEntities:[]}),error=>{assert.ok(error instanceof AppError);assert.equal(error.code,"GROQ_COMPOUND_REQUEST_TOO_LARGE");assert.equal(error.statusCode,503);const details=error.details as Record<string,unknown>;assert.equal(details.provider,"groq");assert.equal(details.providerCode,"request_too_large");assert.equal(details.requestId,"req_413_test");assert.equal(typeof details.requestBodyBytes,"number");assert.ok(Number(details.requestBodyBytes)>0);assert.ok(Number(details.requestBodyBytes)<=65_536);return true})}finally{post.mock.restore()}});
test("topic research defaults to three Compound Mini candidates and adds local embeddings",async()=>{const candidates=[0,1,2].map(index=>({...candidate,topic:`Topic ${index}`,title:`Title ${index}`}));const post=mock.method(axios,"post",async(url:string,body:unknown,config:{headers?:Record<string,string>})=>{const request=body as{model:string;messages:Array<{content:string}>;response_format:{type:string};compound_custom:{tools:{enabled_tools:string[]}}};assert.equal(url,"https://api.groq.test/openai/v1/chat/completions");assert.equal(request.model,"groq/compound-mini");assert.match(request.messages[0].content,/^Research 3 factual short-video topics/);assert.deepEqual(request.response_format,{type:"json_object"});assert.deepEqual(request.compound_custom.tools.enabled_tools,["web_search"]);assert.equal(config.headers?.Authorization,"Bearer test-key");assert.equal(config.headers?.["Groq-Model-Version"],"2025-07-23");return{data:{choices:[{message:{content:`\`\`json\n${JSON.stringify(candidates)}\n\`\``}}]}}});try{const service=new TopicResearchService("test-key","groq/compound-mini","https://api.groq.test/openai/v1/");const result=await service.generate({profile,language:"en",region:"US",recentTopics:[],recentEntities:[]});assert.equal(result.length,3);assert.equal(result[0].embedding?.length,96);assert.equal(post.mock.callCount(),1)}finally{post.mock.restore()}});
test("research normalizes Groq source objects into URL strings",async()=>{
  const candidates=[0,1,2].map(index=>({
    ...candidate,
    topic:`Object Source Topic ${index}`,
    title:`Object Source Title ${index}`,
    sourceLinks:[
      {url:`https://example.org/${index}/primary`,title:"Primary source"},
      `https://example.org/${index}/secondary`,
      {url:`https://example.org/${index}/primary`,title:"Duplicate source"},
      {url:"not-a-url",title:"Invalid source"}
    ]
  }));
  const post=mock.method(axios,"post",async()=>({data:{choices:[{message:{content:JSON.stringify({candidates})}}]}}));
  try{
    const service=new TopicResearchService("test-key","groq/compound-mini","https://api.groq.test/openai/v1");
    const result=await service.generate({profile,language:"en",region:"US",recentTopics:[],recentEntities:[]});
    assert.deepEqual(result[0].sourceLinks,["https://example.org/0/primary","https://example.org/0/secondary"]);
  }finally{post.mock.restore()}
});
test("research falls back from Compound Mini to Qwen then Llama after HTTP 429",async()=>{const candidates=[0,1,2].map(index=>({...candidate,topic:`Fallback Topic ${index}`,title:`Fallback Title ${index}`}));const requests:Array<Record<string,unknown>>=[];const post=mock.method(axios,"post",async(_url:string,body:unknown)=>{const request=body as Record<string,unknown>;requests.push(request);if(requests.length<3)throw{isAxiosError:true,message:"Request failed with status code 429",response:{status:429,data:{error:{message:"Rate limit reached",code:"rate_limit_exceeded"}},headers:{}}};return{data:{choices:[{message:{content:JSON.stringify({candidates})}}]}}});try{const service=new TopicResearchService("test-key","groq/compound-mini","https://api.groq.test/openai/v1",["qwen/qwen3.6-27b","llama-3.1-8b-instant"]);const result=await service.generate({profile,language:"en",region:"US",recentTopics:[],recentEntities:[]});assert.equal(result.length,3);assert.deepEqual(requests.map(request=>request.model),["groq/compound-mini","qwen/qwen3.6-27b","llama-3.1-8b-instant"]);assert.deepEqual((requests[0].compound_custom as{tools:{enabled_tools:string[]}}).tools.enabled_tools,["web_search"]);assert.equal("compound_custom" in requests[1],false);assert.equal(requests[1].reasoning_effort,"none");assert.match(String((requests[1].messages as Array<{content:string}>)[0].content),/Live web search is unavailable/);assert.equal("compound_custom" in requests[2],false);assert.equal("reasoning_effort" in requests[2],false)}finally{post.mock.restore()}});
test("research fallback configuration declares and wires both exact model defaults",()=>{const envSource=fs.readFileSync(new URL("../src/config/env.ts",import.meta.url),"utf8");const containerSource=fs.readFileSync(new URL("../src/config/container.ts",import.meta.url),"utf8");assert.match(envSource,/GROQ_TOPIC_RESEARCH_FALLBACK_MODEL:\s*z\.string\(\)\.default\("qwen\/qwen3\.6-27b"\)/);assert.match(envSource,/GROQ_TOPIC_RESEARCH_SECONDARY_FALLBACK_MODEL:\s*z\.string\(\)\.default\("llama-3\.1-8b-instant"\)/);assert.match(containerSource,/env\.GROQ_TOPIC_RESEARCH_FALLBACK_MODEL/);assert.match(containerSource,/env\.GROQ_TOPIC_RESEARCH_SECONDARY_FALLBACK_MODEL/)});

const validProject={name:"Daily History",contentType:"FACELESS_NICHE",nicheId:"world_history",accountId:"account-1",language:"en",timezone:"Asia/Manila",uploadTime:"19:00",visualType:"AUTO",automationMode:"approval_before_upload",automationEnabled:true};
test("creating a project requires every unified setup field",()=>{assert.equal(createProjectBodySchema.safeParse(validProject).success,true);assert.equal(createProjectBodySchema.safeParse({...validProject,accountId:""}).success,false)});
test("approval before upload is the validation default",()=>{const result=createProjectBodySchema.parse({...validProject,automationMode:undefined});assert.equal(result.automationMode,"approval_before_upload")});
test("visual type replaces story-format mode and defaults to auto",()=>{const result=createProjectBodySchema.parse({...validProject,visualType:undefined,storyFormatMode:"manual_select"});assert.equal(result.visualType,"AUTO");assert.equal("storyFormatMode" in result,false)});
test("image and animated visual types are saved correctly",()=>{assert.equal(createProjectBodySchema.parse({...validProject,visualType:"IMAGE"}).visualType,"IMAGE");assert.equal(createProjectBodySchema.parse({...validProject,visualType:"ANIMATED"}).visualType,"ANIMATED")});
test("faceless projects cannot be created without a niche",()=>assert.equal(createProjectBodySchema.safeParse({...validProject,nicheId:undefined}).success,false));
test("reddit configuration requires sources outside auto mode",()=>{const base={...validProject,contentType:"REDDIT_STORY",nicheId:undefined,redditConfig:{sourceMode:"MULTIPLE_SUBREDDITS",subreddits:[],sortMethod:"BEST_ELIGIBLE",minimumScore:50,minimumComments:10,minimumBodyLength:300,allowNSFW:false,includeComments:false,excludeLocked:true,contentFilters:[],attributionMode:"link",allowCrossAccountReuse:false}};assert.equal(createProjectBodySchema.safeParse(base).success,false);assert.equal(createProjectBodySchema.safeParse({...base,redditConfig:{...base.redditConfig,subreddits:["AskReddit"]}}).success,true)});
test("clip projects do not require a niche",()=>assert.equal(createProjectBodySchema.safeParse({...validProject,contentType:"CLIP_UPLOAD",nicheId:undefined}).success,true));
test("all requested story formats are available",()=>{for(const format of ["shocking_fact","hidden_history","mystery_reveal","rise_and_fall","record_breaking_moment","hero_story","rivalry","controversy","tragedy","unsolved_mystery","myth_versus_fact","what_really_happened","unexpected_ending","one_decision_changed_everything","psychological_explanation"])assert.ok(STORY_FORMATS.includes(format as never))});
test("niche profiles expose reusable automatic settings",()=>{const niche=new NicheConfigService().getNicheOrThrow("psychology");assert.ok(niche.defaultTone);assert.ok(niche.allowedStoryFormats.length);assert.ok(niche.researchRequirements.length);assert.equal(niche.defaultLanguage,niche.language)});
test("timezone date keys enforce one local story per day",()=>{const schedule=new ScheduleService();assert.equal(schedule.localDateKey("Asia/Manila",new Date("2026-07-13T16:30:00Z")),"2026-07-14")});
test("generation idempotency is stable per project date",()=>{assert.equal(workflowIdempotencyKey("p1","2026-07-13","generation"),"p1:2026-07-13:generation");assert.equal(workflowIdempotencyKey("p1","2026-07-13","generation"),workflowIdempotencyKey("p1","2026-07-13","generation"))});
test("daily idempotency keys are type-specific",()=>{assert.equal(projectDailyIdempotencyKey("p1","2026-07-13","FACELESS_NICHE"),"p1:2026-07-13:FACELESS_GENERATION");assert.equal(projectDailyIdempotencyKey("p1","2026-07-13","REDDIT_STORY"),"p1:2026-07-13:REDDIT_FETCH");assert.equal(projectDailyIdempotencyKey("p1","2026-07-13","CLIP_UPLOAD"),"p1:2026-07-13:CLIP_UPLOAD")});
test("upload idempotency is separate from generation",()=>assert.notEqual(workflowIdempotencyKey("p1","2026-07-13","generation"),workflowIdempotencyKey("p1","2026-07-13","upload")));
test("BullMQ job IDs exclude reserved colons",()=>{const id=bullmqJobId(projectDailyIdempotencyKey("p1","2026-07-13","FACELESS_NICHE"));assert.equal(id,"p1_2026-07-13_FACELESS_GENERATION");assert.doesNotMatch(id,/:/)});
test("automation retries stay queued with the provider rate-limit policy",()=>{assert.deepEqual(automationRetryOptions(),{attempts:1000,backoff:{type:"provider-rate-limit"}})});
test("provider retry delays are exactly 30, 60, then 120 seconds",()=>{assert.deepEqual([1,2,3,4].map(providerRetryDelayMs),[30000,60000,120000,120000])});
test("provider retry delay honors a positive numeric retry-after header",()=>{const limited=new AppError("rate",429,"GROQ_RATE_LIMITED",{retryAfter:"75"});assert.equal(providerRetryDelayMs(1,limited),75000);const malformed=new AppError("rate",429,"GROQ_RATE_LIMITED",{retryAfter:"soon"});assert.equal(providerRetryDelayMs(1,malformed),30000)});
test("research response and small Compound 413 failures retry only during the first two retries",()=>{const invalid=new AppError("invalid",502,"RESEARCH_RESPONSE_INVALID");const insufficient=new AppError("short",422,"INSUFFICIENT_RESEARCH_CANDIDATES");const compound413=new AppError("oversized",503,"GROQ_COMPOUND_REQUEST_TOO_LARGE");assert.equal(isRetryableResearchFailure(invalid),true);assert.equal(isRetryableResearchFailure(insufficient),true);assert.equal(isRetryableResearchFailure(compound413),true);assert.equal(isRetryableResearchFailure(new AppError("bad",422,"INVALID")),false);assert.deepEqual([0,1,2].map(attempts=>shouldRetryResearchFailure(invalid,attempts)),[true,true,false]);assert.deepEqual([0,1,2].map(attempts=>shouldRetryResearchFailure(compound413,attempts)),[true,true,false])});
test("automation worker options pace only automation and honor provider retry-after",async()=>{const options=createWorkerOptions({} as never);assert.equal(options.shared.limiter,undefined);assert.deepEqual(options.automation.limiter,AUTOMATION_RATE_LIMITER);assert.deepEqual(AUTOMATION_RATE_LIMITER,{max:1,duration:60000});const strategy=options.automation.settings?.backoffStrategy;assert.ok(strategy);const limited=new AppError("rate",429,"GROQ_RATE_LIMITED",{retryAfter:"75"});assert.equal(await strategy(1,"provider-rate-limit",limited,{} as never),75000)});
test("automation retries rate limits indefinitely but bounds malformed research",()=>{const rate=new AppError("rate",429,"GROQ_RATE_LIMITED");const invalid=new AppError("invalid",502,"RESEARCH_RESPONSE_INVALID");assert.equal(shouldRetryAutomationFailure(rate,999),true);assert.deepEqual([0,1,2].map(attempts=>shouldRetryAutomationFailure(invalid,attempts)),[true,true,false]);assert.equal(shouldRetryAutomationFailure(new AppError("bad",422,"INVALID"),0),false)});
test("provider failure metadata logs safe Groq quota and request diagnostics without secrets",()=>{const error=new AppError("rate",429,"GROQ_RATE_LIMITED",{provider:"groq",providerCode:"rate_limit_exceeded",providerMessage:"TPM exceeded",retryAfter:"75",requestId:"req_safe",requestBodyBytes:1133,limitRequests:"250",remainingRequests:"241",resetRequests:"51m",limitTokens:"70000",remainingTokens:"1200",resetTokens:"48s",apiKey:"must-not-log",prompt:"must-not-log"});const wrapped=new Error("permanent",{cause:error});const metadata=providerFailureMetadata(wrapped);assert.deepEqual(metadata,{errorCode:"GROQ_RATE_LIMITED",statusCode:429,provider:"groq",providerCode:"rate_limit_exceeded",providerMessage:"TPM exceeded",retryAfter:"75",requestId:"req_safe",requestBodyBytes:1133,limitRequests:"250",remainingRequests:"241",resetRequests:"51m",limitTokens:"70000",remainingTokens:"1200",resetTokens:"48s"});assert.equal("apiKey" in metadata,false);assert.equal("prompt" in metadata,false)});
test("story jobs use the provider rate-limit backoff",async()=>{let options:unknown;const queue={add:async(_name:string,_payload:unknown,nextOptions:unknown)=>{options=nextOptions;return{id:"story"}}};await new QueueService({story:queue} as never).addStoryJob({projectId:"p1"});assert.deepEqual(options,{attempts:1000,backoff:{type:"provider-rate-limit"}})});
test("a failed automation job is removed before the same daily ID is requeued",async()=>{let removed=false,adds=0;const failed={isFailed:async()=>true,remove:async()=>{removed=true}};const queue={getJob:async()=>failed,add:async()=>{adds+=1;return{id:"daily"}}};const service=new QueueService({automation:queue} as never);const result=await service.addAutomationJob({projectId:"p1"},{jobId:"daily"});assert.equal(removed,true);assert.equal(adds,1);assert.equal(result.id,"daily")});
test("duration validation requests safe expansion and shortening",()=>{const validator=new DurationValidator();assert.equal(validator.validate("too short",60,150).adjustment,"expand");assert.equal(validator.validate(Array(250).fill("word").join(" "),60,150).adjustment,"shorten")});
test("temporary failures retry while permanent validation errors stop",()=>{assert.equal(isTemporaryFailure(new AppError("rate",429,"RATE_LIMITED")),true);assert.equal(isTemporaryFailure(new AppError("bad",422,"INVALID")),false)});
test("provider HTTP 429 is treated as a rate limit",()=>{assert.equal(isRateLimitFailure(new AppError("rate",429,"RATE_LIMITED")),true);assert.equal(isRateLimitFailure(new AppError("queued",429,"AUTOMATION_JOB_QUEUED")),false);assert.equal(isQueuedWorkflowFailure(new AppError("queued",429,"AUTOMATION_JOB_QUEUED")),true);assert.equal(isRateLimitFailure(new AppError("server",503,"UPSTREAM")),false)});
test("the active-story coordinator queues a second project",async()=>{let value:string|null=null;const redis={set:async(_key:string,next:string)=>{if(value)return null;value=next;return"OK"},get:async()=>value,eval:async(script:string)=>{if(script.includes("expire"))return 0;value=null;return 1}};const coordinator=new AutomationRunCoordinator(redis as never);await coordinator.begin("p1","p1:2026-07-14:FACELESS_GENERATION");await assert.rejects(()=>coordinator.begin("p2","p2:2026-07-14:FACELESS_GENERATION"),error=>error instanceof AppError&&error.code==="AUTOMATION_JOB_QUEUED");await coordinator.finish("p1");await coordinator.begin("p2","p2:2026-07-14:FACELESS_GENERATION")});
test("legacy entry points are removed and unified project APIs are registered",()=>{const handler=(_request?:unknown,_response?:unknown,next?:()=>void)=>next?.();const controller=new Proxy({}, {get:()=>handler}) as never;const router=createProjectRoutes(controller) as unknown as {stack:Array<{route?:{path:string}}>};const paths=router.stack.flatMap((layer)=>layer.route?[layer.route.path]:[]);for(const removed of ["/reddit/trending","/:projectId/run","/:projectId/generate-script","/:projectId/generate-audio","/:projectId/generate-scenes","/:projectId/render","/:projectId/publish"])assert.equal(paths.includes(removed),false);for(const expected of ["/niches","/niches/seed","/reddit/validate","/:projectId/reddit/fetch-now","/:projectId/clips","/:projectId/clips/:clipId/upload-now"])assert.ok(paths.includes(expected),expected)});
test("migration preserves history and archives the obsolete profile collection",()=>{const migration=fs.readFileSync(new URL("../src/migrations/20260713-unify-project-automation.ts",import.meta.url),"utf8");assert.match(migration,/renderProjectId/);assert.match(migration,/legacy_nicheautomations_archived_20260713/);assert.doesNotMatch(migration,/platformVideoId\s*:/);assert.doesNotMatch(migration,/deleteMany\(\{\}\)/)});

test("project creation validates the account and persists the unified settings",async()=>{let saved:Record<string,unknown>|undefined;const repository={logActivity:async()=>({})};const projects={createAutomationProject:async(input:Record<string,unknown>)=>{saved=input;return{_id:"p1",id:"p1",userId:"u1"}}};const channels={findByIdAndUserId:async()=>({id:"a1",title:"Channel",externalChannelId:"youtube-1",status:"connected",refreshToken:"refresh"})};const service=new AutomationService(repository as never,new NicheConfigService(),{} as never,channels as never,{} as never,projects as never,{} as never,{} as never,{} as never,{} as never);await service.createProject("u1",validProject as never);assert.equal(saved?.name,"Daily History");assert.equal(saved?.accountId,"account-1");assert.equal(saved?.automationMode,"approval_before_upload");assert.ok(saved?.nextRunAt instanceof Date)});
test("complete project generation uses the shared renderer with automatic niche settings",async()=>{let historyInput:Record<string,unknown>|undefined;let started="";const repository={findByGenerationKey:async()=>null,findComparisonHistory:async()=>[],createHistory:async(input:Record<string,unknown>)=>{historyInput=input;return{id:"story-1"}},createRejected:async()=>({}),logActivity:async()=>({})};const root={id:"p1",_id:"p1",userId:"u1",projectType:"faceless_story",contentType:"FACELESS_NICHE",visualType:"AUTO",facelessSource:"daily_automation",internalStory:false,nicheId:"sports",accountId:"a1",timezone:"Asia/Manila",uploadTime:"19:00",language:"en",durationSeconds:60,storyFormatMode:"auto_select",automationMode:"approval_before_upload"};const projects={getProjectOrThrow:async()=>root,updateProject:async()=>root};const channels={findById:async()=>({id:"a1",title:"Sports Channel",status:"connected",refreshToken:"refresh"})};const faceless={createGeneratedStoryProject:async()=>({id:"render-1",_id:"render-1"}),startAutomation:async(id:string)=>{started=id;return{id}}};const research={generate:async()=>[candidate]};const service=new AutomationService(repository as never,new NicheConfigService(),research as never,channels as never,faceless as never,projects as never,{} as never,{} as never,{} as never,{} as never);const result=await service.execute("p1","2026-07-13");assert.equal(started,"render-1");assert.deepEqual(result.contentIds,["story-1"]);assert.equal(historyInput?.targetDurationSeconds,60);assert.equal(historyInput?.generationIdempotencyKey,"p1:2026-07-13:FACELESS_GENERATION");assert.ok(historyInput?.voiceId)});
test("daily Reddit automation selects a fresh source and reuses the faceless renderer",async()=>{let renderInput:Record<string,unknown>|undefined;let historyInput:Record<string,unknown>|undefined;const repository={findByGenerationKey:async()=>null,findComparisonHistory:async()=>[],createHistory:async(input:Record<string,unknown>)=>{historyInput=input;return{id:"story-r",_id:"story-r"}},createRejected:async()=>({}),logActivity:async()=>({})};const root={id:"reddit-project",_id:"reddit-project",userId:"u1",projectType:"faceless_story",contentType:"REDDIT_STORY",visualType:"ANIMATED",facelessSource:"daily_automation",internalStory:false,accountId:"a1",timezone:"Asia/Manila",uploadTime:"19:00",language:"en",durationSeconds:60,automationMode:"approval_before_upload"};const projects={getProjectOrThrow:async()=>root,updateProject:async()=>root};const channels={findById:async()=>({id:"a1",title:"Reddit Channel",status:"connected",refreshToken:"refresh"})};const faceless={createGeneratedStoryProject:async(input:Record<string,unknown>)=>{renderInput=input;return{id:"render-r",_id:"render-r"}},startAutomation:async()=>({})};const record={id:"source-r",updateOne:async()=>({})};const reddit={select:async()=>({candidate,record})};const service=new AutomationService(repository as never,new NicheConfigService(),{} as never,channels as never,faceless as never,projects as never,{} as never,{} as never,{} as never,{} as never,reddit as never);await service.execute("reddit-project","2026-07-13");assert.equal(renderInput?.facelessRenderMode,"animation_story");assert.equal(historyInput?.nicheId,"reddit:reddit-project");assert.equal(historyInput?.generationIdempotencyKey,"reddit-project:2026-07-13:REDDIT_FETCH")});

test("Generate Now makes the completed story due immediately",async()=>{
  let historyInput:Record<string,unknown>|undefined;
  const repository={findByGenerationKey:async()=>null,findComparisonHistory:async()=>[],createHistory:async(input:Record<string,unknown>)=>{historyInput=input;return{id:"story-manual"}},createRejected:async()=>({}),logActivity:async()=>({})};
  const root={id:"manual-project",_id:"manual-project",userId:"u1",projectType:"faceless_story",contentType:"FACELESS_NICHE",visualType:"AUTO",facelessSource:"daily_automation",internalStory:false,nicheId:"sports",accountId:"a1",timezone:"Asia/Manila",uploadTime:"19:00",language:"en",durationSeconds:60,automationMode:"fully_automatic"};
  const projects={getProjectOrThrow:async()=>root,updateProject:async()=>root};
  const channels={findById:async()=>({id:"a1",title:"Sports Channel",status:"connected",refreshToken:"refresh"})};
  const faceless={createGeneratedStoryProject:async()=>({id:"render-manual",_id:"render-manual"}),startAutomation:async()=>({})};
  const research={generate:async()=>[candidate]};
  const service=new AutomationService(repository as never,new NicheConfigService(),research as never,channels as never,faceless as never,projects as never,{} as never,{} as never,{} as never,{} as never);
  const before=Date.now();
  await service.execute("manual-project","2026-08-11","manual");
  const after=Date.now();
  const scheduledUploadTime=historyInput?.scheduledUploadTime;
  assert.ok(scheduledUploadTime instanceof Date);
  assert.ok(scheduledUploadTime.getTime()>=before && scheduledUploadTime.getTime()<=after);
});

test("reconcile continues with later stories after one story fails quality preparation",async()=>{
  const updates:Array<{id:string;status:unknown}>=[];
  const repository={
    findPendingFinalization:async()=>[
      {id:"broken",projectId:"root-broken",renderProjectId:"render-broken",accountId:"a1",status:"quality_check"},
      {id:"later",projectId:"root-later",renderProjectId:"render-later",accountId:"a1",status:"quality_check"}
    ],
    updateHistory:async(id:string,input:{status?:unknown})=>{updates.push({id,status:input.status});return{id,...input}}
  };
  const root={id:"root-later",_id:"root-later",userId:"u1",automationMode:"fully_automatic",automationEnabled:true};
  const projects={getProjectOrThrow:async(id:string)=>{if(id==="root-broken")throw new Error("missing render output");return id==="render-later"?{id,status:"rendering"}:root}};
  const assets={findScript:async()=>null,findLatestAssetByType:async()=>null,findRender:async()=>null,findAssets:async()=>[]};
  const channels={findById:async()=>({id:"a1",status:"connected",refreshToken:"refresh"})};
  const service=new AutomationService(repository as never,new NicheConfigService(),{} as never,channels as never,{} as never,projects as never,assets as never,{} as never,{} as never,{} as never);
  const results=await service.reconcile();
  assert.ok(results.some((result)=>result instanceof Error));
  assert.deepEqual(updates,[{id:"later",status:"rendering"}]);
});

test("default niche profiles expose every persistent field",()=>{const profiles=new NicheConfigService().listNiches();assert.deepEqual(profiles.map((item)=>item.name),["Sports","World History","Philippine History","Mysteries","Psychology","Science","True Stories"]);for(const item of profiles){assert.ok(item.id&&item.slug&&item.description&&item.active);assert.ok(item.voicePreferences&&item.visualPreferences.length&&item.researchRequirements.length)}});
test("default niche seed uses idempotent upserts",async()=>{let operations:unknown[]=[];const bulk=mock.method(NicheProfileModel,"bulkWrite",async(value:unknown[])=>{operations=value;return{} as never});const count=mock.method(NicheProfileModel,"countDocuments",async()=>7 as never);try{const result=await new NicheConfigService().seedDefaults();assert.equal(result.total,7);assert.equal(operations.length,7);assert.ok(operations.every((item)=>Boolean((item as {updateOne?:{upsert?:boolean;update?:{$setOnInsert?:unknown}}}).updateOne?.upsert&&(item as {updateOne:{update:{$setOnInsert?:unknown}}}).updateOne.update.$setOnInsert)))}finally{bulk.mock.restore();count.mock.restore()}});
test("active niche API source returns seeded defaults when database is unavailable",async()=>assert.equal((await new NicheConfigService().listActiveNiches()).length,7));

test("Reddit authenticates through the official OAuth API",async()=>{const request=mock.fn(async()=>new Response(JSON.stringify({access_token:"token",expires_in:3600}),{status:200,headers:{"content-type":"application/json"}}));const result=await new RedditApiClient("client","secret","agent",request as never).testConnection();assert.equal(result.officialApi,true);assert.equal(request.mock.callCount(),1)});
test("failed Reddit authentication retries temporary responses",async()=>{let attempts=0;const request=mock.fn(async()=>{attempts+=1;return new Response(attempts<3?"temporary":JSON.stringify({access_token:"token"}),{status:attempts<3?500:200,headers:{"content-type":"application/json"}})});await new RedditApiClient("client","secret","agent",request as never).testConnection();assert.equal(attempts,3)});

const redditConfig={projectId:"p1",sourceMode:"MULTIPLE_SUBREDDITS",subreddits:["AskReddit"],sortMethod:"BEST_ELIGIBLE",minimumScore:10,minimumComments:2,minimumBodyLength:80,allowNSFW:false,includeComments:false,excludeLocked:true,contentFilters:[],attributionMode:"link",allowCrossAccountReuse:false} as never;
const redditPost=(overrides:Partial<RedditPost>={}):RedditPost=>({id:"post-1",subreddit:"AskReddit",permalink:"https://reddit.test/post-1",title:"What unexpected secret did you discover?",body:"A complete emotional account ".repeat(20),author:"private_user",createdUtc:Date.now()/1000-3600,score:500,comments:80,nsfw:false,stickied:false,locked:false,removed:false,advertisement:false,...overrides});
test("Reddit ranking filters deleted, pinned, NSFW, locked, and duplicate posts",()=>{const service=new RedditService({} as never);const posts=[redditPost(),redditPost({id:"deleted",removed:true}),redditPost({id:"pinned",stickied:true}),redditPost({id:"nsfw",nsfw:true}),redditPost({id:"locked",locked:true}),redditPost({id:"duplicate"})];const result=service.filterAndRank(posts,redditConfig,{ids:new Set(["duplicate"])});assert.deepEqual(result.map((item)=>item.id),["post-1"])});
test("Reddit transformation anonymizes PII and labels claims as submissions",()=>{const service=new RedditService({} as never);const text=service.sanitize("u/realperson wrote real@example.com and +1 555 123 4567");assert.doesNotMatch(text,/realperson|real@example|555/);assert.match(service.toCandidate(redditPost()).summary,/Reddit user submitted/)});
test("Reddit content hashes and source IDs are protected by unique indexes",()=>{const serialized=JSON.stringify(RedditSourceModel.schema.indexes());assert.match(serialized,/redditPostId/);assert.match(serialized,/permalink/);assert.match(serialized,/contentHash/)});

test("clip file and media validation rejects unsupported or corrupt input",()=>{assert.equal(isSupportedClipMime("video/mp4"),true);assert.equal(isSupportedClipMime("text/plain"),false);assert.equal(validateClipMedia({durationSeconds:60,width:1080,height:1920,hasAudio:true}),true);assert.equal(validateClipMedia({durationSeconds:0,width:1080,height:1920,hasAudio:true}),false);assert.equal(validateClipMedia({durationSeconds:60,width:1080,height:1920,hasAudio:false}),false)});
test("clip upload idempotency is stable and account-specific",()=>{assert.equal(clipUploadIdempotencyKey("clip","account"),"clip:account:CLIP_UPLOAD");assert.notEqual(clipUploadIdempotencyKey("clip","a"),clipUploadIdempotencyKey("clip","b"))});
test("clip queue has duplicate-file, schedule, status, and platform indexes",()=>{const serialized=JSON.stringify(QueuedClipModel.schema.indexes());assert.match(serialized,/sourceFileHash/);assert.match(serialized,/scheduledAt/);assert.match(serialized,/status/);assert.match(serialized,/platformVideoId/)});
